# Generated by Django 2.2.10 on 2021-09-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210907_0722'),
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='choice',
        ),
        migrations.AddField(
            model_name='vote',
            name='choice',
            field=models.ManyToManyField(to='core.Choice'),
        ),
    ]
