# Generated by Django 2.2.10 on 2021-09-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_auto_20210907_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='choice',
            field=models.ManyToManyField(blank=True, to='core.Choice'),
        ),
    ]
