# Generated by Django 2.2.10 on 2021-09-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_vote_text_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='text_answer',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
