# Generated by Django 2.2.10 on 2021-09-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='answer',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
