# Generated by Django 2.2.10 on 2021-09-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210907_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontype',
            name='qtype',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
